[2025-08-10T20:38:13.222+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:38:13.223+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:38:13.225+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:38:13.224+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:38:13.238+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:38:13.237+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:38:13.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:38:13.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.038 seconds
[2025-08-10T20:38:43.512+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:38:43.513+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:38:43.514+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:38:43.514+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:38:43.524+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:38:43.523+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:38:43.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:38:43.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.034 seconds
[2025-08-10T20:39:13.845+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:39:13.846+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:39:13.848+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:39:13.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:39:13.873+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:39:13.871+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:39:13.875+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:39:13.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.053 seconds
[2025-08-10T20:39:44.103+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:39:44.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:39:44.106+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:39:44.106+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:39:44.115+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:39:44.115+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:39:44.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:39:44.133+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.034 seconds
[2025-08-10T20:40:14.382+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:40:14.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:40:14.386+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:40:14.385+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:40:14.411+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:40:14.410+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:40:14.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:40:14.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.053 seconds
[2025-08-10T20:40:44.619+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:40:44.620+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:40:44.622+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:40:44.621+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:40:44.646+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:40:44.645+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:40:44.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:40:44.665+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.051 seconds
[2025-08-10T20:41:15.021+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:41:15.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:41:15.028+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:41:15.028+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:41:15.068+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:41:15.066+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:41:15.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:41:15.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.078 seconds
[2025-08-10T20:41:45.285+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:41:45.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:41:45.288+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:41:45.287+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:41:45.299+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:41:45.298+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:41:45.300+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:41:45.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.036 seconds
[2025-08-10T20:42:15.597+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:42:15.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:42:15.600+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:42:15.600+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:42:15.614+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:42:15.613+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:42:15.614+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:42:15.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.037 seconds
[2025-08-10T20:42:45.928+0000] {processor.py:161} INFO - Started process (PID=221) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:42:45.929+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:42:45.931+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:42:45.931+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:42:45.941+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:42:45.940+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:42:45.941+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:42:45.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.033 seconds
[2025-08-10T20:43:16.274+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:43:16.275+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:43:16.277+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:43:16.276+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:43:16.288+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:43:16.287+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:43:16.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:43:16.304+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.035 seconds
[2025-08-10T20:43:46.629+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:43:46.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:43:46.632+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:43:46.632+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:43:46.683+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:43:46.681+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:43:46.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:43:46.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.089 seconds
[2025-08-10T20:44:16.808+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:44:16.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:44:16.810+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:44:16.810+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:44:16.821+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:44:16.820+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:44:16.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:44:16.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.035 seconds
[2025-08-10T20:44:47.132+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:44:47.133+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:44:47.135+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:44:47.134+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:44:47.147+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:44:47.145+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:44:47.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:44:47.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.037 seconds
[2025-08-10T20:45:17.461+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:45:17.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:45:17.463+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:45:17.463+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:45:17.473+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:45:17.473+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:45:17.474+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:45:17.490+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.033 seconds
[2025-08-10T20:45:47.770+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:45:47.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:45:47.773+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:45:47.773+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:45:47.785+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:45:47.784+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:45:47.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:45:47.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.036 seconds
[2025-08-10T20:46:18.079+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:46:18.080+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:46:18.082+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:46:18.081+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:46:18.095+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:46:18.094+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:46:18.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:46:18.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.035 seconds
[2025-08-10T20:46:48.435+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:46:48.436+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:46:48.439+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:46:48.439+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:46:48.462+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:46:48.461+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:46:48.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:46:48.488+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.061 seconds
[2025-08-10T20:47:18.762+0000] {processor.py:161} INFO - Started process (PID=266) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:47:18.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:47:18.765+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:47:18.765+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:47:18.774+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:47:18.773+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:47:18.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:47:18.791+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.033 seconds
[2025-08-10T20:47:49.160+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:47:49.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:47:49.163+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:47:49.163+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:47:49.173+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:47:49.172+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:47:49.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:47:49.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.034 seconds
[2025-08-10T20:48:19.534+0000] {processor.py:161} INFO - Started process (PID=276) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:48:19.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:48:19.537+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:48:19.536+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:48:19.551+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:48:19.550+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:48:19.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:48:19.567+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.041 seconds
[2025-08-10T20:48:49.817+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:48:49.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:48:49.819+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:48:49.819+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:48:49.830+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:48:49.829+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:48:49.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:48:49.847+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.036 seconds
[2025-08-10T20:49:20.054+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:49:20.055+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:49:20.056+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:49:20.056+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:49:20.068+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:49:20.067+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:49:20.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:49:20.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.038 seconds
[2025-08-10T20:49:50.333+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:49:50.333+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:49:50.336+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:49:50.335+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:49:50.345+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:49:50.345+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:49:50.346+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:49:50.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.032 seconds
[2025-08-10T20:50:20.633+0000] {processor.py:161} INFO - Started process (PID=296) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:50:20.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:50:20.636+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:50:20.636+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:50:20.645+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:50:20.645+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:50:20.646+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:50:20.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.033 seconds
[2025-08-10T20:50:50.934+0000] {processor.py:161} INFO - Started process (PID=301) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:50:50.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:50:50.937+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:50:50.936+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:50:50.951+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:50:50.950+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:50:50.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:50:50.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.035 seconds
[2025-08-10T20:51:21.215+0000] {processor.py:161} INFO - Started process (PID=306) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:51:21.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:51:21.217+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:51:21.217+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:51:21.230+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:51:21.229+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:51:21.231+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:51:21.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.037 seconds
[2025-08-10T20:51:51.620+0000] {processor.py:161} INFO - Started process (PID=311) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:51:51.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:51:51.623+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:51:51.623+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:51:51.662+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:51:51.661+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:51:51.663+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:51:51.681+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.066 seconds
[2025-08-10T20:52:21.863+0000] {processor.py:161} INFO - Started process (PID=316) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:52:21.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:52:21.866+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:52:21.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:52:21.883+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:52:21.882+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:52:21.884+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:52:21.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.045 seconds
[2025-08-10T20:52:52.170+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:52:52.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:52:52.173+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:52:52.172+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:52:52.185+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:52:52.184+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:52:52.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:52:52.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.034 seconds
[2025-08-10T20:53:22.513+0000] {processor.py:161} INFO - Started process (PID=326) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:53:22.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:53:22.515+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:53:22.515+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:53:22.531+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:53:22.530+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:53:22.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:53:22.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.040 seconds
[2025-08-10T20:53:52.729+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:53:52.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:53:52.734+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:53:52.733+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:53:52.744+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:53:52.744+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:53:52.745+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:53:52.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.036 seconds
[2025-08-10T20:54:22.939+0000] {processor.py:161} INFO - Started process (PID=336) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:54:22.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:54:22.941+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:54:22.941+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:54:22.952+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:54:22.951+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:54:22.952+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:54:22.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.033 seconds
[2025-08-10T20:54:53.133+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:54:53.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:54:53.136+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:54:53.136+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:54:53.148+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:54:53.147+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:54:53.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:54:53.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.035 seconds
[2025-08-10T20:55:23.307+0000] {processor.py:161} INFO - Started process (PID=346) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:55:23.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:55:23.309+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:55:23.308+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:55:23.324+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:55:23.323+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:55:23.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:55:23.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.039 seconds
[2025-08-10T20:55:53.535+0000] {processor.py:161} INFO - Started process (PID=351) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:55:53.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:55:53.537+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:55:53.537+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:55:53.548+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:55:53.547+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:55:53.549+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:55:53.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.034 seconds
[2025-08-10T20:56:23.748+0000] {processor.py:161} INFO - Started process (PID=356) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:56:23.749+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:56:23.751+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:56:23.750+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:56:23.760+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:56:23.759+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:56:23.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:56:23.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.033 seconds
[2025-08-10T20:56:54.076+0000] {processor.py:161} INFO - Started process (PID=361) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:56:54.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:56:54.078+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:56:54.078+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:56:54.087+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:56:54.086+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:56:54.087+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:56:54.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.031 seconds
[2025-08-10T20:57:24.420+0000] {processor.py:161} INFO - Started process (PID=366) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:57:24.421+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:57:24.423+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:57:24.423+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:57:24.439+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:57:24.438+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:57:24.439+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:57:24.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.042 seconds
[2025-08-10T20:57:54.690+0000] {processor.py:161} INFO - Started process (PID=371) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:57:54.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:57:54.692+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:57:54.692+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:57:54.709+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:57:54.708+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:57:54.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:57:54.727+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.041 seconds
[2025-08-10T20:58:25.031+0000] {processor.py:161} INFO - Started process (PID=376) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:58:25.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:58:25.033+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:58:25.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:58:25.045+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:58:25.044+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:58:25.045+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:58:25.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.036 seconds
[2025-08-10T20:58:55.230+0000] {processor.py:161} INFO - Started process (PID=381) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:58:55.231+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:58:55.232+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:58:55.232+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:58:55.255+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:58:55.253+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:58:55.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:58:55.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.048 seconds
[2025-08-10T20:59:25.423+0000] {processor.py:161} INFO - Started process (PID=386) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:59:25.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:59:25.426+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:59:25.425+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:59:25.447+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:59:25.446+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:59:25.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:59:25.466+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.047 seconds
[2025-08-10T20:59:55.682+0000] {processor.py:161} INFO - Started process (PID=391) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:59:55.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T20:59:55.684+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:59:55.684+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:59:55.696+0000] {logging_mixin.py:188} INFO - [2025-08-10T20:59:55.695+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T20:59:55.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T20:59:55.711+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.033 seconds
[2025-08-10T21:00:25.867+0000] {processor.py:161} INFO - Started process (PID=396) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:00:25.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:00:25.870+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:00:25.870+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:00:25.886+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:00:25.885+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:00:25.887+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:00:25.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.040 seconds
[2025-08-10T21:00:56.125+0000] {processor.py:161} INFO - Started process (PID=401) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:00:56.126+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:00:56.127+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:00:56.127+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:00:56.137+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:00:56.136+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:00:56.137+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:00:56.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.031 seconds
[2025-08-10T21:01:26.465+0000] {processor.py:161} INFO - Started process (PID=406) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:01:26.466+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:01:26.467+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:01:26.467+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:01:26.481+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:01:26.480+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:01:26.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:01:26.499+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.039 seconds
[2025-08-10T21:01:56.666+0000] {processor.py:161} INFO - Started process (PID=411) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:01:56.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:01:56.668+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:01:56.667+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:01:56.685+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:01:56.684+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:01:56.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:01:56.703+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.041 seconds
[2025-08-10T21:02:26.937+0000] {processor.py:161} INFO - Started process (PID=416) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:02:26.938+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:02:26.939+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:02:26.939+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:02:26.948+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:02:26.948+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:02:26.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:02:26.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.032 seconds
[2025-08-10T21:02:57.324+0000] {processor.py:161} INFO - Started process (PID=421) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:02:57.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:02:57.340+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:02:57.339+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:02:57.382+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:02:57.379+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:02:57.389+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:02:57.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.112 seconds
[2025-08-10T21:03:27.612+0000] {processor.py:161} INFO - Started process (PID=426) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:03:27.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:03:27.615+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:03:27.615+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:03:27.627+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:03:27.626+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:03:27.628+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:03:27.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.037 seconds
[2025-08-10T21:03:57.804+0000] {processor.py:161} INFO - Started process (PID=431) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:03:57.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:03:57.807+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:03:57.806+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:03:57.819+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:03:57.818+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:03:57.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:03:57.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.035 seconds
[2025-08-10T21:04:28.282+0000] {processor.py:161} INFO - Started process (PID=436) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:04:28.284+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:04:28.286+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:04:28.286+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:04:28.309+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:04:28.308+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:04:28.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:04:28.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.054 seconds
[2025-08-10T21:04:58.427+0000] {processor.py:161} INFO - Started process (PID=441) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:04:58.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:04:58.430+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:04:58.429+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:04:58.442+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:04:58.441+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:04:58.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:04:58.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.037 seconds
[2025-08-10T21:05:28.690+0000] {processor.py:161} INFO - Started process (PID=446) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:05:28.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:05:28.693+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:05:28.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:05:28.721+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:05:28.720+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:05:28.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:05:28.740+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.057 seconds
[2025-08-10T21:05:58.934+0000] {processor.py:161} INFO - Started process (PID=451) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:05:58.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:05:58.937+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:05:58.937+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:05:58.961+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:05:58.960+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:05:58.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:05:58.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.051 seconds
[2025-08-10T21:06:29.177+0000] {processor.py:161} INFO - Started process (PID=456) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:06:29.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:06:29.180+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:06:29.180+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:06:29.212+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:06:29.211+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:06:29.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:06:29.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.060 seconds
[2025-08-10T21:06:59.378+0000] {processor.py:161} INFO - Started process (PID=461) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:06:59.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:06:59.380+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:06:59.380+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:06:59.392+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:06:59.391+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:06:59.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:06:59.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.036 seconds
[2025-08-10T21:07:29.633+0000] {processor.py:161} INFO - Started process (PID=466) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:07:29.634+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:07:29.636+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:07:29.636+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:07:29.667+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:07:29.666+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:07:29.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:07:29.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.060 seconds
[2025-08-10T21:07:59.899+0000] {processor.py:161} INFO - Started process (PID=471) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:07:59.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:07:59.901+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:07:59.901+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:07:59.911+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:07:59.911+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:07:59.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:07:59.927+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.033 seconds
[2025-08-10T21:08:30.134+0000] {processor.py:161} INFO - Started process (PID=476) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:08:30.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:08:30.136+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:08:30.136+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:08:30.149+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:08:30.149+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:08:30.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:08:30.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.042 seconds
[2025-08-10T21:09:00.461+0000] {processor.py:161} INFO - Started process (PID=481) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:09:00.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:09:00.465+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:09:00.464+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:09:00.518+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:09:00.517+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:09:00.520+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:09:00.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.093 seconds
[2025-08-10T21:09:30.729+0000] {processor.py:161} INFO - Started process (PID=486) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:09:30.730+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:09:30.732+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:09:30.732+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:09:30.775+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:09:30.773+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:09:30.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:09:30.799+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.076 seconds
[2025-08-10T21:10:01.055+0000] {processor.py:161} INFO - Started process (PID=491) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:10:01.057+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:10:01.059+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:10:01.059+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:10:01.098+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:10:01.096+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:10:01.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:10:01.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.077 seconds
[2025-08-10T21:10:31.544+0000] {processor.py:161} INFO - Started process (PID=496) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:10:31.546+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:10:31.549+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:10:31.548+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:10:31.593+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:10:31.592+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:10:31.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:10:31.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.082 seconds
[2025-08-10T21:11:01.791+0000] {processor.py:161} INFO - Started process (PID=501) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:11:01.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:11:01.795+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:11:01.795+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:11:01.843+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:11:01.842+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:11:01.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:11:01.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.088 seconds
[2025-08-10T21:11:32.154+0000] {processor.py:161} INFO - Started process (PID=506) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:11:32.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:11:32.157+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:11:32.157+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:11:32.188+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:11:32.186+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:11:32.189+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:11:32.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.066 seconds
[2025-08-10T21:12:02.416+0000] {processor.py:161} INFO - Started process (PID=511) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:12:02.417+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:12:02.419+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:12:02.418+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:12:02.468+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:12:02.467+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:12:02.469+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:12:02.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.087 seconds
[2025-08-10T21:12:32.721+0000] {processor.py:161} INFO - Started process (PID=516) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:12:32.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:12:32.728+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:12:32.728+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:12:32.818+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:12:32.816+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:12:32.819+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:12:32.867+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.156 seconds
[2025-08-10T21:13:03.217+0000] {processor.py:161} INFO - Started process (PID=521) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:13:03.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:13:03.231+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:13:03.225+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:13:03.292+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:13:03.290+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:13:03.294+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:13:03.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.127 seconds
[2025-08-10T21:13:33.645+0000] {processor.py:161} INFO - Started process (PID=526) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:13:33.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:13:33.652+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:13:33.651+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:13:33.717+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:13:33.715+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:13:33.718+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:13:33.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.126 seconds
[2025-08-10T21:14:03.990+0000] {processor.py:161} INFO - Started process (PID=531) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:14:03.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:14:03.995+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:14:03.995+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:14:04.054+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:14:04.049+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:14:04.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:14:04.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.120 seconds
[2025-08-10T21:14:34.447+0000] {processor.py:161} INFO - Started process (PID=536) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:14:34.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:14:34.454+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:14:34.453+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:14:34.522+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:14:34.520+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:14:34.524+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:14:34.577+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.138 seconds
[2025-08-10T21:15:04.865+0000] {processor.py:161} INFO - Started process (PID=541) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:15:04.867+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:15:04.871+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:15:04.871+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:15:04.936+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:15:04.930+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:15:04.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:15:04.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.127 seconds
[2025-08-10T21:15:35.357+0000] {processor.py:161} INFO - Started process (PID=546) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:15:35.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:15:35.362+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:15:35.362+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:15:35.409+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:15:35.407+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:15:35.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:15:35.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.119 seconds
[2025-08-10T21:16:05.769+0000] {processor.py:161} INFO - Started process (PID=551) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:16:05.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:16:05.774+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:16:05.773+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:16:05.839+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:16:05.835+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:16:05.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:16:05.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.123 seconds
[2025-08-10T21:16:36.173+0000] {processor.py:161} INFO - Started process (PID=556) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:16:36.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:16:36.189+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:16:36.188+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:16:36.254+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:16:36.252+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:16:36.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:16:36.289+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.127 seconds
[2025-08-10T21:17:06.549+0000] {processor.py:161} INFO - Started process (PID=561) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:17:06.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:17:06.554+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:17:06.553+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:17:06.598+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:17:06.596+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:17:06.599+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:17:06.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.098 seconds
[2025-08-10T21:17:36.975+0000] {processor.py:161} INFO - Started process (PID=566) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:17:36.977+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:17:36.980+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:17:36.980+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:17:37.040+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:17:37.039+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:17:37.042+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:17:37.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.117 seconds
[2025-08-10T21:18:07.338+0000] {processor.py:161} INFO - Started process (PID=571) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:18:07.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:18:07.344+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:18:07.343+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:18:07.401+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:18:07.399+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:18:07.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:18:07.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.110 seconds
[2025-08-10T21:18:37.875+0000] {processor.py:161} INFO - Started process (PID=576) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:18:37.877+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:18:37.881+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:18:37.881+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:18:37.941+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:18:37.939+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:18:37.943+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:18:37.987+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.123 seconds
[2025-08-10T21:19:08.217+0000] {processor.py:161} INFO - Started process (PID=581) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:19:08.220+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:19:08.223+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:19:08.222+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:19:08.271+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:19:08.269+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_pipeline_dag.py", line 157
    bash_command=(
                 ^
SyntaxError: '(' was never closed
[2025-08-10T21:19:08.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:19:08.347+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.140 seconds
[2025-08-10T21:19:27.629+0000] {processor.py:161} INFO - Started process (PID=586) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:19:27.631+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:19:27.634+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:19:27.634+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:19:27.714+0000] {processor.py:840} INFO - DAG(s) 'sales_pipeline' retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:19:28.176+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:19:28.175+0000] {override.py:1858} INFO - Created Permission View: can read on DAG:sales_pipeline
[2025-08-10T21:19:28.196+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:19:28.196+0000] {override.py:1858} INFO - Created Permission View: can edit on DAG:sales_pipeline
[2025-08-10T21:19:28.209+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:19:28.209+0000] {override.py:1858} INFO - Created Permission View: can delete on DAG:sales_pipeline
[2025-08-10T21:19:28.211+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:19:28.211+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2025-08-10T21:19:28.234+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:19:28.233+0000] {dag.py:3111} INFO - Creating ORM DAG for sales_pipeline
[2025-08-10T21:19:28.256+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:19:28.256+0000] {dag.py:3947} INFO - Setting next_dagrun for sales_pipeline to 2025-08-10 21:00:00+00:00, run_after=2025-08-10 21:15:00+00:00
[2025-08-10T21:19:28.304+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.682 seconds
[2025-08-10T21:20:09.179+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:20:09.181+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:20:09.183+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:20:09.183+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:20:09.217+0000] {processor.py:840} INFO - DAG(s) 'sales_pipeline' retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:20:09.261+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:20:09.260+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2025-08-10T21:20:09.284+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:20:09.283+0000] {dag.py:3947} INFO - Setting next_dagrun for sales_pipeline to 2025-08-10 21:00:00+00:00, run_after=2025-08-10 21:15:00+00:00
[2025-08-10T21:20:09.306+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.133 seconds
[2025-08-10T21:20:39.640+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:20:39.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:20:39.646+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:20:39.646+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:20:39.706+0000] {processor.py:840} INFO - DAG(s) 'sales_pipeline' retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:20:39.764+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:20:39.764+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2025-08-10T21:20:39.807+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:20:39.806+0000] {dag.py:3947} INFO - Setting next_dagrun for sales_pipeline to 2025-08-10 21:00:00+00:00, run_after=2025-08-10 21:15:00+00:00
[2025-08-10T21:20:39.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.227 seconds
[2025-08-10T21:21:10.030+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:21:10.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:21:10.036+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:21:10.035+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:21:10.095+0000] {processor.py:840} INFO - DAG(s) 'sales_pipeline' retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:21:10.149+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:21:10.149+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2025-08-10T21:21:10.179+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:21:10.179+0000] {dag.py:3947} INFO - Setting next_dagrun for sales_pipeline to 2025-08-10 21:00:00+00:00, run_after=2025-08-10 21:15:00+00:00
[2025-08-10T21:21:10.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.190 seconds
[2025-08-10T21:21:40.630+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:21:40.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:21:40.637+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:21:40.636+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:21:40.704+0000] {processor.py:840} INFO - DAG(s) 'sales_pipeline' retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:21:40.761+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:21:40.760+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2025-08-10T21:21:40.784+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:21:40.784+0000] {dag.py:3947} INFO - Setting next_dagrun for sales_pipeline to 2025-08-10 21:00:00+00:00, run_after=2025-08-10 21:15:00+00:00
[2025-08-10T21:21:40.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.188 seconds
[2025-08-10T21:22:10.973+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:22:10.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:22:10.978+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:22:10.978+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:22:11.033+0000] {processor.py:840} INFO - DAG(s) 'sales_pipeline' retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:22:11.074+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:22:11.074+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2025-08-10T21:22:11.099+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:22:11.098+0000] {dag.py:3947} INFO - Setting next_dagrun for sales_pipeline to 2025-08-10 21:15:00+00:00, run_after=2025-08-10 21:30:00+00:00
[2025-08-10T21:22:11.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.155 seconds
[2025-08-10T21:22:41.472+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:22:41.474+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:22:41.479+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:22:41.478+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:22:41.544+0000] {processor.py:840} INFO - DAG(s) 'sales_pipeline' retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:22:41.602+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:22:41.601+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2025-08-10T21:22:41.633+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:22:41.633+0000] {dag.py:3947} INFO - Setting next_dagrun for sales_pipeline to 2025-08-10 21:15:00+00:00, run_after=2025-08-10 21:30:00+00:00
[2025-08-10T21:22:41.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.203 seconds
[2025-08-10T21:23:12.010+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:23:12.012+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:23:12.016+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:23:12.016+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:23:12.081+0000] {processor.py:840} INFO - DAG(s) 'sales_pipeline' retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:23:12.130+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:23:12.130+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2025-08-10T21:23:12.165+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:23:12.165+0000] {dag.py:3947} INFO - Setting next_dagrun for sales_pipeline to 2025-08-10 21:15:00+00:00, run_after=2025-08-10 21:30:00+00:00
[2025-08-10T21:23:12.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.198 seconds
[2025-08-10T21:23:42.387+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:23:42.389+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:23:42.393+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:23:42.392+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:23:42.450+0000] {processor.py:840} INFO - DAG(s) 'sales_pipeline' retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:23:42.498+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:23:42.498+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2025-08-10T21:23:42.518+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:23:42.518+0000] {dag.py:3947} INFO - Setting next_dagrun for sales_pipeline to 2025-08-10 21:15:00+00:00, run_after=2025-08-10 21:30:00+00:00
[2025-08-10T21:23:42.538+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.160 seconds
[2025-08-10T21:24:12.878+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:24:12.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:24:12.884+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:24:12.883+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:24:12.946+0000] {processor.py:840} INFO - DAG(s) 'sales_pipeline' retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:24:13.005+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:24:13.004+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2025-08-10T21:24:13.047+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:24:13.047+0000] {dag.py:3947} INFO - Setting next_dagrun for sales_pipeline to 2025-08-10 21:15:00+00:00, run_after=2025-08-10 21:30:00+00:00
[2025-08-10T21:24:13.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.220 seconds
[2025-08-10T21:24:43.377+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:24:43.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_pipeline_dag.py for tasks to queue
[2025-08-10T21:24:43.383+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:24:43.382+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:24:43.446+0000] {processor.py:840} INFO - DAG(s) 'sales_pipeline' retrieved from /opt/airflow/dags/sales_pipeline_dag.py
[2025-08-10T21:24:43.507+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:24:43.507+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2025-08-10T21:24:43.548+0000] {logging_mixin.py:188} INFO - [2025-08-10T21:24:43.548+0000] {dag.py:3947} INFO - Setting next_dagrun for sales_pipeline to 2025-08-10 21:15:00+00:00, run_after=2025-08-10 21:30:00+00:00
[2025-08-10T21:24:43.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_pipeline_dag.py took 0.231 seconds
